- name: Run database container
  community.docker.docker_container:
    name: database
    image: "{{ DOCKERHUB_USERNAME }}/tp-devops-database:latest"
    pull: true
    state: started
    restart_policy: always
    recreate: true
    networks:
      - name: app-network
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd