- name: Run front container
  community.docker.docker_container:
    name: front
    image: "{{ DOCKERHUB_USERNAME }}/tp-devops-front:latest"
    pull: true
    networks:
      - name: app-network
    restart_policy: unless-stopped