name: SonarCloud

on:
  workflow_run:
    workflows: ["Test Backend"]
    types:
      - completed
    branches:
      - main
      - develop

jobs:
  sonarcloud:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Analyze with SonarCloud
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=SimonGIR_tp2-docker -Dsonar.organization=simongir -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file ./simple-api/pom.xml